// Generated by CoffeeScript 1.6.3
var albumes;

$(document).ready(function() {
  return $("#buscador").keyup(function() {
    var i, texto, _i, _len, _ref, _results;
    texto = $("#buscador").val().toUpperCase();
    modelo.amigos([]);
    _ref = modelo.backup();
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      if (btn_m || btn_f) {
        if (i.name.toUpperCase().indexOf(texto) !== -1 && btn_m && i.gender !== "female") {
          _results.push(modelo.amigos.push(i));
        } else if (i.name.toUpperCase().indexOf(texto) !== -1 && btn_f && i.gender !== "male") {
          _results.push(modelo.amigos.push(i));
        } else {
          _results.push(void 0);
        }
      } else {
        if (i.name.toUpperCase().indexOf(texto) !== -1) {
          _results.push(modelo.amigos.push(i));
        } else {
          _results.push(void 0);
        }
      }
    }
    return _results;
  });
});

albumes = function(id) {
  window.fbAsyncInit = function() {
    return FB.init({
      appId: '686818771334811',
      cookie: true,
      xfbml: true,
      version: 'v2.0'
    });
  };
  return FB.getLoginStatus(function(response) {
    if (response.status === "not_authorized" || response.status === "unknown") {
      window.location = window.location.origin;
      return "no autorizado o desconectado";
    }
    return FB.api("/" + id, function(response) {
      console.log(response, "lol");
      return response;
    });
  });
};
