// Generated by CoffeeScript 1.6.3
var app, body_parser, express, php;

express = require("express");

php = require("php-express")({
  binPath: '/usr/bin/php'
});

body_parser = require("body-parser");

app = express();

app.use(body_parser.json());

app.set("views", __dirname + "/views");

app.engine("php", php.engine);

app.set("view engine", "php");

app.get("/", function(request, response) {
  return response.render("index");
});

app.listen(3030);
