// Generated by CoffeeScript 1.6.3
var body_parser, express, servidor;

express = require("express");

body_parser = require("body-parser");

servidor = express();

servidor.use(body_parser.json());

servidor.use(express["static"](__dirname));

servidor.get("/hola/mundo", function(request, response) {
  console.log(request.get("user-agent"));
  response.set("Content-Type", "text/plain");
  response.status(200);
  return response.send("Hola :)");
});

servidor.get("/index/chafa", function(request, response) {
  response.set("Content-Type", "text/html");
  response.status(200);
  return response.send("<section><article><p style='font-weight:bold;font-size:40px;'>Hola super mundo</p></article><article><a href='/index'>click</a></section>");
});

servidor.get("/index", function(request, response) {
  response.set("Content-Type", "text/html");
  response.status(200);
  return response.sendfile("index.html");
});

servidor.get("*", function(request, response) {
  response.set("Content-Type", "text/plain");
  response.status(404);
  return response.send("NOT FOUND");
});

servidor.listen(3030);

console.log("Escuchando puerto 3030");
