// Generated by CoffeeScript 1.6.3
var app, express, port;

express = require('express');

app = express();

port = 8080;

app.use(express["static"](__dirname + '/html'));

app.use("/css", express["static"](__dirname + "/html/css"));

app.get("/", function(request, response) {
  return response.sendfile("index.html", {
    root: __dirname + "/html"
  });
});

console.log('Escuchando en el puerto ' + 8080);

app.listen(port);
